try {
  console.lo("num1");
} catch (err) {
  console.log(err);
  console.log(err.message)
  console.log(err.name)
}
